<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Microsoft.AspNetCore.Routing">
			<HintPath>..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.0\Microsoft.AspNetCore.Routing.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cardboard.Device\Cardboard.Device.csproj" />
		<ProjectReference Include="..\Cardboard.Repositories\Cardboard.Repositories.csproj" />
		<ProjectReference Include="..\Cardboard.Update\Cardboard.Update.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
	</ItemGroup>
</Project>
