<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cardboard.Device\Cardboard.Device.csproj" />
		<ProjectReference Include="..\Cardboard.Events\Cardboard.Events.csproj" />
		<ProjectReference Include="..\Cardboard.Repositories\Cardboard.Repositories.csproj" />
		<ProjectReference Include="..\Cardboard.Utilities\Cardboard.Utilities.csproj" />
	</ItemGroup>
</Project>
