<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Microsoft.Extensions.Options">
			<HintPath>..\..\..\..\..\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.0\Microsoft.Extensions.Options.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cardboard.Update\Cardboard.Update.csproj" />
	</ItemGroup>
</Project>
