<Project Sdk="Microsoft.NET.Sdk.Worker">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Cardboard.RemoteServer-7bd6e80a-1acc-436e-9db3-827f2515d962</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="files\**\*" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cardboard.Api\Cardboard.Api.csproj" />
		<ProjectReference Include="..\Cardboard.Update.Api\Cardboard.Update.Api.csproj" />
		<ProjectReference Include="..\Cardboard.Utilities\Cardboard.Utilities.csproj" />
	</ItemGroup>
</Project>
