<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ggbim.Cranky.Events" Version="2.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
      <PackageReference Include="System.Management" Version="9.0.5" />
      <PackageReference Include="System.Reactive" Version="6.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cardboard.Device\Cardboard.Device.csproj" />
      <ProjectReference Include="..\Cardboard.Serial\Cardboard.Serial.csproj" />
      <ProjectReference Include="..\Cardboard.Windows\Cardboard.Windows.csproj" />
    </ItemGroup>

</Project>
